---
# Python yaml load test
name: PythonTest
on:
  push:
    branches:
      - test

jobs:
  Test:
    name: Test 
    runs-on: ubuntu-latest
#     outputs:
#         matrix: ${{ steps.setmatrix.outputs.matrix }}
        
#     strategy:
#       matrix:
#         image:
#           - 'ubuntu2004'
#           - 'centos7'
#           - 'centos8'
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Inline python step
#         id: setmatrix
        run: |
          import yaml
          
          with open('servers.yaml') as fh:
            read_data = yaml.safe_load(fh)
          print(read_data)
          print(read_data["name"])
         
        shell: python
