---
# Python yaml load test
name: PythonTest
on:
  push:
    branches:
      - test

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.setmatrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Inline python step
        id: setmatrix
        run: |
          import yaml
          import json
          
          with open('servers.yaml') as fh:
            read_data = yaml.safe_load(fh)
          vm_list=[]
          for i in read_data:
            vm_list.append(i["name"])
          json_list = json.loads(vm_list)
          print(f"::set-output name=matrix::{json_list}")
          
        shell: python
  
  job2:
    needs: job1
    runs-on: ubuntu-latest
#     strategy:
#        matrix: ${{ fromJSON(needs.job1.outputs.matrix) }}
    steps:
     - run: echo ${{ needs.job1.outputs.matrix }}
